# Generated by Django 5.1.2 on 2024-10-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_posts_identifier_alter_posts_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='identifier',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
